### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Vistaus** [symbuzzer/utchess#1]
It would be great if this app could be translated. I will provide the Dutch translation once that's possible. 🙂

**Comment by symbuzzer** [comment]
Thanks, but it is web-based (PWA) app and I try to update it every day for custom devices. When finalize this, I can accept trasnlation and other things

**Comment by symbuzzer** [comment]
Can I close this for now?
@Vistaus

**Comment by Vistaus** [comment]
As long as it's not implemented, it's still an ‘issue’.

**Comment by symbuzzer** [comment]
So:

**Comment by Vistaus** [comment]
But you said you can accept translations in the future, so what do you mean by “not planned”?

**Comment by symbuzzer** [comment]
I can not I will
